"use strict";

const StudyList = require("../models/StudyList");
const Problem = require("../models/Problem");

const createStudyList = async (req, res) => {
  try {
    const { name, description } = req.body;

    if (!name) {
      return res.status(400).json({\n        success: false,\n        message: "Study list name is required",\n      });\n    }

    const studyList = new StudyList({\n      name,\n      description: description || "",\n      user: req.user._id,\n      problems: [],\n    });\n\n    await studyList.save();\n\n    res.status(201).json({\n      success: true,\n      message: "Study list created successfully",\n      studyList,\n    });\n  } catch (error) {\n    console.error("Create study list error:", error);\n    if (error.name === \"ValidationError\") {\n      return res.status(400).json({\n        success: false,\n        message: error.message,\n      });\n    }\n    res.status(500).json({\n      success: false,\n      message: \"Server error while creating study list\",\n    });\n  }\n};

const getStudyLists = async (req, res) => {
  try {
    const studyLists = await StudyList.find({ user: req.user._id }).populate(\n      "problems\"\n    );\n\n    res.status(200).json({\n      success: true,\n      count: studyLists.length,\n      studyLists,\n    });\n  } catch (error) {\n    console.error("Get study lists error:", error);\n    res.status(500).json({\n      success: false,\n      message: \"Server error while fetching study lists\",\n    });\n  }\n};

const getStudyListById = async (req, res) => {\n  try {\n    const studyList = await StudyList.findById(req.params.id).populate(\"problems\");\n\n    if (!studyList) {\n      return res.status(404).json({\n        success: false,\n        message: \"Study list not found\",\n      });\n    }\n\n    if (!studyList.user.equals(req.user._id)) {\n      return res.status(403).json({\n        success: false,\n        message: \"Access denied\",\n      });\n    }\n\n    res.status(200).json({\n      success: true,\n      studyList,\n    });\n  } catch (error) {\n    console.error(\"Get study list by ID error:\", error);\n    res.status(500).json({\n      success: false,\n      message: \"Server error while fetching study list\",\n    });\n  }\n};\n\nconst addProblemToStudyList = async (req, res) => {\n  try {\n    const { problemId } = req.body;\n\n    if (!problemId) {\n      return res.status(400).json({\n        success: false,\n        message: \"Problem ID is required\",\n      });\n    }\n\n    const studyList = await StudyList.findById(req.params.id);\n\n    if (!studyList) {\n      return res.status(404).json({\n        success: false,\n        message: \"Study list not found\",\n      });\n    }\n\n    if (!studyList.user.equals(req.user._id)) {\n      return res.status(403).json({\n        success: false,\n        message: \"Access denied\",\n      });\n    }\n\n    const problem = await Problem.findById(problemId);\n\n    if (!problem) {\n      return res.status(404).json({\n        success: false,\n        message: \"Problem not found\",\n      });\n    }\n\n    if (!problem.user.equals(req.user._id)) {\n      return res.status(403).json({\
        success: false,\n        message: \"Access denied - cannot add other user's problem\",\n      });\n    }\n\n    if (studyList.problems.includes(problemId)) {\n      return res.status(400).json({\n        success: false,\n        message: \"Problem already in study list\",\n      });\n    }\n\n    studyList.problems.push(problemId);\n    await studyList.save();\n\n    res.status(200).json({\n      success: true,\n      message: \"Problem added to study list successfully\",\n      studyList,\n    });\n  } catch (error) {\n    console.error(\"Add problem to study list error:\", error);\n    res.status(500).json({\n      success: false,\n      message: \"Server error while adding problem to study list\",\n    });\n  }\n};\n\nconst removeProblemFromStudyList = async (req, res) => {\n  try {\n    const { problemId } = req.body;\n\n    if (!problemId) {\n      return res.status(400).json({\n        success: false,\n        message: \"Problem ID is required\",\n      });\n    }\n\n    const studyList = await StudyList.findById(req.params.id);\n\n    if (!studyList) {\n      return res.status(404).json({\n        success: false,\n        message: \"Study list not found\",\n      });\n    }\n\n    if (!studyList.user.equals(req.user._id)) {\n      return res.status(403).json({\n        success: false,\n        message: \"Access denied\",\n      });\n    }\n\n    if (!studyList.problems.includes(problemId)) {\n      return res.status(404).json({\n        success: false,\n        message: \"Problem not found in study list\",\n      });\n    }\n\n    studyList.problems = studyList.problems.filter((id) => id.toString() !== problemId);\n    await studyList.save();\n\n    res.status(200).json({\n      success: true,\n      message: \"Problem removed from study list successfully\",\n      studyList,\n    });\n  } catch (error) {\n    console.error(\"Remove problem from study list error:\", error);\n    res.status(500).json({\n      success: false,\n      message: \"Server error while removing problem from study list\",\n    });\n  }\n};\n\nmodule.exports = {\n  createStudyList,\n  getStudyLists,\n  getStudyListById,\n  addProblemToStudyList,\n  removeProblemFromStudyList,\n};