export const APP_NAME = 'PrepPilot'

export const THEME_TOKENS = {
  bg: '#060816',
  surface: '#0f172a',
  text: '#f8fafc',
  muted: '#94a3b8',
  accent: '#22d3ee',
  accentSoft: '#0f766e',
}

export const DSA_TOPICS = [
  'Arrays',
  'Strings',
  'Hashing',
  'Two Pointers',
  'Sliding Window',
  'Binary Search',
  'Sorting',
  'Recursion',
  'Backtracking',
  'Stack',
  'Queue',
  'Linked List',
  'Trees',
  'Binary Trees',
  'Binary Search Trees',
  'Heaps / Priority Queue',
  'Greedy',
  'Dynamic Programming',
  'Graphs',
  'BFS',
  'DFS',
  'Topological Sort',
  'Union Find (DSU)',
  'Trie',
  'Bit Manipulation',
  'Math',
  'Prefix Sum',
  'Monotonic Stack',
  'Monotonic Queue',
  'Segment Tree',
  'Fenwick Tree (BIT)',
  'Interval Problems',
  'Matrix',
  'Simulation',
  'Design',
  'Geometry',
]
